name: chunked_uploader
description: A plugin to upload files to server in chunks using Dio.
version: 0.1.0
homepage: https://github.com/Taskulu/chunked_uploader
repository: https://github.com/Taskulu/chunked_uploader

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  dio: ^4.0.0
  universal_io: ^2.0.1
