name: chunked_uploader
description: A plugin to upload files to server in chunks using Dio.
version: 0.0.2+1
homepage: https://github.com/Taskulu/chunked_uploader
repository: https://github.com/Taskulu/chunked_uploader

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  path: ^1.7.0
  dio: ^3.0.10
