name: chunk_uploader
description: A plugin to upload files to server in chunks.
version: 0.0.1
homepage: https://github.com/Taskulu/chunked_uploader
repository: https://github.com/Taskulu/chunked_uploader

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.10